after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]

shift-cmd-h = 'focus left'
shift-cmd-j = 'focus down'
shift-cmd-k = 'focus up'
shift-cmd-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-0     = 'balance-sizes'

cmd-d = 'close'

cmd-enter = 'exec-and-forget  /Applications/WezTerm.app/Contents/MacOS/wezterm'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-tab = 'workspace-back-and-forth'

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"


shift-cmd-f = 'layout floating tiling'


[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
# run = ['layout floating', 'move-node-to-workspace 3'] 
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.netease.163music'
run = ['layout floating'] 

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = ['layout floating'] 
